version: '3.7'

services:
  bot:
    container_name: discutaille-discord-bot
    image: ghcr.io/docsystem/discutaille-x-discord:main
    restart: unless-stopped
    environment:
      TOKEN: ${TOKEN}
      HOSTNAME: "https://discutaille-cdn.docsystem.xyz"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.discutaille-discord-bot.rule=Host(`discutaille-cdn.docsystem.xyz`)"
      - "traefik.http.services.discutaille-discord-bot.loadbalancer.server.port=80"